### ISSUE TITLE
ServiceType argument in file is not honoured if missing console flag

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/telemetry-consumers#17]
If you don't pass `--servicetype` to the console command, then you can't run the telemetry consumer as an event processor.

Request is to allow for the configuration and setup of the telemetry consumer type from the config file rather than from the console only.

**Comment by aneeshkp** [comment]
Leif , it’s technical issue . You can’t send servicetype via config file . It has to be command line parameter .

**Comment by leifmadsen** [comment]
@aneeshkp your example configuration file shows that `ServiceType` is a configuration parameter, and since everything else on the command line can be passed as a configuration argument, I consider this a bug.

**Comment by aneeshkp** [comment]
Works as designed . Won’t fix . This flag decides what type of service to run , config will be applied to respective , service type .

**Comment by leifmadsen** [comment]
Then this issue is to fix your configuration example which is invalid.

**Comment by aneeshkp** [comment]
Sure , I thought I had done that . Will look into it and fix the text , if it’s missing .+1
If you run it without any parameter then the helper says about —servicetype as command line arg , just like —config

**Comment by leifmadsen** [comment]
It's not missing, that's the problem. The sample config file is invalid
because it shows ServiceType as a configuration file option but it isn't
honoured.

>

**Comment by leifmadsen** [comment]
Removed invalid configuration option from sample configs.
